// This file was auto-generated by Fern from our API Definition.

export interface GetFriendsResponse {
    data: GetFriendsResponse.Data.Item[];
    pagination: GetFriendsResponse.Pagination;
}

export namespace GetFriendsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            friend: Item.Friend;
            since: string;
        }

        export namespace Item {
            export interface Friend {
                id: string;
                handle: string;
                clerkId?: string;
                createdAt: string;
            }
        }
    }

    export interface Pagination {
        page: number;
        pageSize: number;
        total: number;
    }
}
