// This file was auto-generated by Fern from our API Definition.

export interface GetFriendsIdResponse {
    friend: GetFriendsIdResponse.Friend;
    likes: GetFriendsIdResponse.Likes.Item[];
}

export namespace GetFriendsIdResponse {
    export interface Friend {
        id: string;
        handle: string;
        clerkId?: string;
        createdAt: string;
    }

    export type Likes = Likes.Item[];

    export namespace Likes {
        export interface Item {
            poi: Item.Poi;
            tag: string;
            visibility: Item.Visibility;
            createdAt: string;
            distance_meters?: number;
        }

        export namespace Item {
            export interface Poi {
                id: string;
                name: string;
                description?: string;
                lat: number;
                lng: number;
                createdById?: string;
                appleMapId?: string;
                metadata?: unknown;
                createdAt: string;
            }

            export const Visibility = {
                Public: "PUBLIC",
                Private: "PRIVATE",
                FriendsOnly: "FRIENDS_ONLY",
            } as const;
            export type Visibility = (typeof Visibility)[keyof typeof Visibility];
        }
    }
}
