// This file was auto-generated by Fern from our API Definition.

export interface GetFriendsPendingResponse {
    pending: GetFriendsPendingResponse.Pending.Item[];
}

export namespace GetFriendsPendingResponse {
    export type Pending = Pending.Item[];

    export namespace Pending {
        export interface Item {
            friend: Item.Friend;
            requestedAt: string;
            direction: Item.Direction;
        }

        export namespace Item {
            export interface Friend {
                id: string;
                handle: string;
                clerkId?: string;
                createdAt: string;
            }

            export const Direction = {
                Incoming: "incoming",
                Outgoing: "outgoing",
            } as const;
            export type Direction = (typeof Direction)[keyof typeof Direction];
        }
    }
}
