// This file was auto-generated by Fern from our API Definition.

export interface GetLikesMineResponseItem {
    poi: GetLikesMineResponseItem.Poi;
    tag: string;
    visibility: GetLikesMineResponseItem.Visibility;
    createdAt: string;
}

export namespace GetLikesMineResponseItem {
    export interface Poi {
        id: string;
        name: string;
        description?: string;
        lat: number;
        lng: number;
        createdById?: string;
        appleMapId?: string;
        metadata?: unknown;
        createdAt: string;
    }

    export const Visibility = {
        Public: "PUBLIC",
        Private: "PRIVATE",
        FriendsOnly: "FRIENDS_ONLY",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
