// This file was auto-generated by Fern from our API Definition.

export interface GetLikesMineAggregateNearbyResponseItem {
    poi: GetLikesMineAggregateNearbyResponseItem.Poi;
    count: number;
    distanceMeters: number;
}

export namespace GetLikesMineAggregateNearbyResponseItem {
    export interface Poi {
        id: string;
        name: string;
        description?: string;
        lat: number;
        lng: number;
        createdById?: string;
        appleMapId?: string;
        metadata?: unknown;
        createdAt: string;
    }
}
