// This file was auto-generated by Fern from our API Definition.

export interface GetLikesFriendsAggregateResponseItem {
    poi: GetLikesFriendsAggregateResponseItem.Poi;
    count: number;
}

export namespace GetLikesFriendsAggregateResponseItem {
    export interface Poi {
        id: string;
        name: string;
        description?: string;
        lat: number;
        lng: number;
        createdById?: string;
        appleMapId?: string;
        metadata?: unknown;
        createdAt: string;
    }
}
