// This file was auto-generated by Fern from our API Definition.

export interface GetLikesFriendsResponseItem {
    poi: GetLikesFriendsResponseItem.Poi;
    likedBy: GetLikesFriendsResponseItem.LikedBy;
    tag: string;
    visibility: GetLikesFriendsResponseItem.Visibility;
    createdAt: string;
}

export namespace GetLikesFriendsResponseItem {
    export interface Poi {
        id: string;
        name: string;
        description?: string;
        lat: number;
        lng: number;
        createdById?: string;
        appleMapId?: string;
        metadata?: unknown;
        createdAt: string;
    }

    export interface LikedBy {
        id: string;
        handle: string;
    }

    export const Visibility = {
        Public: "PUBLIC",
        Private: "PRIVATE",
        FriendsOnly: "FRIENDS_ONLY",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
