// This file was auto-generated by Fern from our API Definition.

export interface GetPoisIdResponse {
    poi: GetPoisIdResponse.Poi;
    friends: GetPoisIdResponse.Friends.Item[];
}

export namespace GetPoisIdResponse {
    export interface Poi {
        id: string;
        name: string;
        description?: string;
        lat: number;
        lng: number;
        createdById?: string;
        appleMapId?: string;
        metadata?: unknown;
        createdAt: string;
    }

    export type Friends = Friends.Item[];

    export namespace Friends {
        export interface Item {
            id: string;
            handle: string;
            like: Item.Like;
        }

        export namespace Item {
            export interface Like {
                tag: string;
                visibility: Like.Visibility;
                createdAt: string;
            }

            export namespace Like {
                export const Visibility = {
                    Public: "PUBLIC",
                    Private: "PRIVATE",
                    FriendsOnly: "FRIENDS_ONLY",
                } as const;
                export type Visibility = (typeof Visibility)[keyof typeof Visibility];
            }
        }
    }
}
