// This file was auto-generated by Fern from our API Definition.

export interface GetPoisResponseItem {
    poi: GetPoisResponseItem.Poi;
    friend_likes: number;
    status: GetPoisResponseItem.Status;
}

export namespace GetPoisResponseItem {
    export interface Poi {
        id: string;
        name: string;
        description?: string;
        lat: number;
        lng: number;
        createdById?: string;
        appleMapId?: string;
        metadata?: unknown;
        createdAt: string;
    }

    export const Status = {
        Liked: "Liked",
        NotLiked: "Not Liked",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
