// This file was auto-generated by Fern from our API Definition.

export interface PostPoisResponse {
    poi: PostPoisResponse.Poi;
    status: PostPoisResponse.Status;
}

export namespace PostPoisResponse {
    export interface Poi {
        id: string;
        name: string;
        description?: string;
        lat: number;
        lng: number;
        createdById?: string;
        appleMapId?: string;
        metadata?: unknown;
        createdAt: string;
    }

    export const Status = {
        Liked: "Liked",
        NotLiked: "Not Liked",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
