// This file was auto-generated by Fern from our API Definition.

export interface PostLikesResponse {
    userId: string;
    poiId: string;
    tag: string;
    visibility: PostLikesResponse.Visibility;
    createdAt: string;
}

export namespace PostLikesResponse {
    export const Visibility = {
        Public: "PUBLIC",
        Private: "PRIVATE",
        FriendsOnly: "FRIENDS_ONLY",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
