// This file was auto-generated by Fern from our API Definition.

export class SpotApiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, SpotApiTimeoutError.prototype);
    }
}
