// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         page: 1,
 *         pageSize: 1
 *     }
 */
export interface GetFriendsRequest {
    page?: number;
    pageSize?: number;
}
