// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "userId",
 *         limit: 1
 *     }
 */
export interface GetLikesMineRequest {
    userId: string;
    limit?: number;
}
