// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "userId",
 *         lat: 1.1,
 *         lng: 1.1,
 *         limit: 1
 *     }
 */
export interface GetLikesFriendsAggregateNearbyRequest {
    userId: string;
    lat: number;
    lng: number;
    limit?: number;
}
