// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         lat: 1.1,
 *         long: 1.1,
 *         page: 1,
 *         pageSize: 1
 *     }
 */
export interface GetPoisRequest {
    lat: number;
    long: number;
    page?: number;
    pageSize?: number;
}
