// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         lat: 1.1,
 *         lng: 1.1
 *     }
 */
export interface PostPoisRequest {
    name: string;
    description?: string;
    lat: number;
    lng: number;
    createdById?: string;
    appleMapId?: string;
    metadata?: Record<string, unknown>;
    tag?: string;
    visibility?: PostPoisRequest.Visibility;
}

export namespace PostPoisRequest {
    export const Visibility = {
        Public: "PUBLIC",
        Private: "PRIVATE",
        FriendsOnly: "FRIENDS_ONLY",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
