// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userId: "userId",
 *         poiId: "poiId",
 *         tag: "tag"
 *     }
 */
export interface PostLikesRequest {
    userId: string;
    poiId: string;
    tag: string;
    visibility?: PostLikesRequest.Visibility;
}

export namespace PostLikesRequest {
    export const Visibility = {
        Public: "PUBLIC",
        Private: "PRIVATE",
        FriendsOnly: "FRIENDS_ONLY",
    } as const;
    export type Visibility = (typeof Visibility)[keyof typeof Visibility];
}
