// This file was auto-generated by Fern from our API Definition.

import * as SpotApi from "./api/index.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";
import * as errors from "./errors/index.js";

export declare namespace SpotApiClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SpotApiClient {
    protected readonly _options: SpotApiClient.Options;

    constructor(_options: SpotApiClient.Options = {}) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    /**
     * Discover POIs near a location
     *
     * @param {SpotApi.GetPoisRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getPois({
     *         lat: 1.1,
     *         long: 1.1,
     *         page: 1,
     *         pageSize: 1
     *     })
     */
    public getPois(
        request: SpotApi.GetPoisRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetPoisResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__getPois(request, requestOptions));
    }

    private async __getPois(
        request: SpotApi.GetPoisRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetPoisResponseItem[]>> {
        const { lat, long, page, pageSize } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.lat = lat.toString();
        _queryParams.long = long.toString();
        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (pageSize != null) {
            _queryParams.pageSize = pageSize.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "pois",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as SpotApi.GetPoisResponseItem[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /pois.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a POI and like it as the current user
     *
     * @param {SpotApi.PostPoisRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.postPois({
     *         name: "name",
     *         lat: 1.1,
     *         lng: 1.1
     *     })
     */
    public postPois(
        request: SpotApi.PostPoisRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.PostPoisResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postPois(request, requestOptions));
    }

    private async __postPois(
        request: SpotApi.PostPoisRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.PostPoisResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "pois",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as SpotApi.PostPoisResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling POST /pois.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch a POI and the friends who liked it
     *
     * @param {string} id
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.NotFoundError}
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getPoisId("id")
     */
    public getPoisId(
        id: string,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetPoisIdResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPoisId(id, requestOptions));
    }

    private async __getPoisId(
        id: string,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetPoisIdResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                `pois/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as SpotApi.GetPoisIdResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new SpotApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /pois/{id}.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a like for a POI
     *
     * @param {SpotApi.PostLikesRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.NotFoundError}
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.postLikes({
     *         userId: "userId",
     *         poiId: "poiId",
     *         tag: "tag"
     *     })
     */
    public postLikes(
        request: SpotApi.PostLikesRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.PostLikesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postLikes(request, requestOptions));
    }

    private async __postLikes(
        request: SpotApi.PostLikesRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.PostLikesResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "likes",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as SpotApi.PostLikesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new SpotApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling POST /likes.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch likes created by friends that are visible to the user
     *
     * @param {SpotApi.GetLikesFriendsRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getLikesFriends({
     *         userId: "userId",
     *         limit: 1
     *     })
     */
    public getLikesFriends(
        request: SpotApi.GetLikesFriendsRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetLikesFriendsResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__getLikesFriends(request, requestOptions));
    }

    private async __getLikesFriends(
        request: SpotApi.GetLikesFriendsRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetLikesFriendsResponseItem[]>> {
        const { userId, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.userId = userId;
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "likes/friends",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as SpotApi.GetLikesFriendsResponseItem[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /likes/friends.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch likes created by the current user
     *
     * @param {SpotApi.GetLikesMineRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getLikesMine({
     *         userId: "userId",
     *         limit: 1
     *     })
     */
    public getLikesMine(
        request: SpotApi.GetLikesMineRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetLikesMineResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__getLikesMine(request, requestOptions));
    }

    private async __getLikesMine(
        request: SpotApi.GetLikesMineRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetLikesMineResponseItem[]>> {
        const { userId, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.userId = userId;
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "likes/mine",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as SpotApi.GetLikesMineResponseItem[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /likes/mine.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch visible friend likes aggregated per POI
     *
     * @param {SpotApi.GetLikesFriendsAggregateRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getLikesFriendsAggregate({
     *         userId: "userId",
     *         limit: 1
     *     })
     */
    public getLikesFriendsAggregate(
        request: SpotApi.GetLikesFriendsAggregateRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetLikesFriendsAggregateResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__getLikesFriendsAggregate(request, requestOptions));
    }

    private async __getLikesFriendsAggregate(
        request: SpotApi.GetLikesFriendsAggregateRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetLikesFriendsAggregateResponseItem[]>> {
        const { userId, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.userId = userId;
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "likes/friends/aggregate",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as SpotApi.GetLikesFriendsAggregateResponseItem[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /likes/friends/aggregate.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch the current user’s likes aggregated per POI
     *
     * @param {SpotApi.GetLikesMineAggregateRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getLikesMineAggregate({
     *         userId: "userId",
     *         limit: 1
     *     })
     */
    public getLikesMineAggregate(
        request: SpotApi.GetLikesMineAggregateRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetLikesMineAggregateResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__getLikesMineAggregate(request, requestOptions));
    }

    private async __getLikesMineAggregate(
        request: SpotApi.GetLikesMineAggregateRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetLikesMineAggregateResponseItem[]>> {
        const { userId, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.userId = userId;
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "likes/mine/aggregate",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as SpotApi.GetLikesMineAggregateResponseItem[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /likes/mine/aggregate.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch visible friend likes aggregated per POI sorted by proximity
     *
     * @param {SpotApi.GetLikesFriendsAggregateNearbyRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getLikesFriendsAggregateNearby({
     *         userId: "userId",
     *         lat: 1.1,
     *         lng: 1.1,
     *         limit: 1
     *     })
     */
    public getLikesFriendsAggregateNearby(
        request: SpotApi.GetLikesFriendsAggregateNearbyRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetLikesFriendsAggregateNearbyResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__getLikesFriendsAggregateNearby(request, requestOptions));
    }

    private async __getLikesFriendsAggregateNearby(
        request: SpotApi.GetLikesFriendsAggregateNearbyRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetLikesFriendsAggregateNearbyResponseItem[]>> {
        const { userId, lat, lng, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.userId = userId;
        _queryParams.lat = lat.toString();
        _queryParams.lng = lng.toString();
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "likes/friends/aggregate/nearby",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as SpotApi.GetLikesFriendsAggregateNearbyResponseItem[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError(
                    "Timeout exceeded when calling GET /likes/friends/aggregate/nearby.",
                );
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch the current user’s aggregated likes ordered by proximity
     *
     * @param {SpotApi.GetLikesMineAggregateNearbyRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getLikesMineAggregateNearby({
     *         userId: "userId",
     *         lat: 1.1,
     *         lng: 1.1,
     *         limit: 1
     *     })
     */
    public getLikesMineAggregateNearby(
        request: SpotApi.GetLikesMineAggregateNearbyRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetLikesMineAggregateNearbyResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__getLikesMineAggregateNearby(request, requestOptions));
    }

    private async __getLikesMineAggregateNearby(
        request: SpotApi.GetLikesMineAggregateNearbyRequest,
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetLikesMineAggregateNearbyResponseItem[]>> {
        const { userId, lat, lng, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.userId = userId;
        _queryParams.lat = lat.toString();
        _queryParams.lng = lng.toString();
        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "likes/mine/aggregate/nearby",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as SpotApi.GetLikesMineAggregateNearbyResponseItem[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /likes/mine/aggregate/nearby.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List approved friends
     *
     * @param {SpotApi.GetFriendsRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getFriends({
     *         page: 1,
     *         pageSize: 1
     *     })
     */
    public getFriends(
        request: SpotApi.GetFriendsRequest = {},
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetFriendsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getFriends(request, requestOptions));
    }

    private async __getFriends(
        request: SpotApi.GetFriendsRequest = {},
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetFriendsResponse>> {
        const { page, pageSize } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (pageSize != null) {
            _queryParams.pageSize = pageSize.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "friends",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as SpotApi.GetFriendsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /friends.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List pending friend requests
     *
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getFriendsPending()
     */
    public getFriendsPending(
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetFriendsPendingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getFriendsPending(requestOptions));
    }

    private async __getFriendsPending(
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetFriendsPendingResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                "friends/pending",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as SpotApi.GetFriendsPendingResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /friends/pending.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch a friend profile and their liked POIs
     *
     * @param {string} id
     * @param {SpotApi.GetFriendsIdRequest} request
     * @param {SpotApiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link SpotApi.NotFoundError}
     * @throws {@link SpotApi.InternalServerError}
     *
     * @example
     *     await client.getFriendsId("id", {
     *         lat: 1.1,
     *         long: 1.1
     *     })
     */
    public getFriendsId(
        id: string,
        request: SpotApi.GetFriendsIdRequest = {},
        requestOptions?: SpotApiClient.RequestOptions,
    ): core.HttpResponsePromise<SpotApi.GetFriendsIdResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getFriendsId(id, request, requestOptions));
    }

    private async __getFriendsId(
        id: string,
        request: SpotApi.GetFriendsIdRequest = {},
        requestOptions?: SpotApiClient.RequestOptions,
    ): Promise<core.WithRawResponse<SpotApi.GetFriendsIdResponse>> {
        const { lat, long } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (lat != null) {
            _queryParams.lat = lat.toString();
        }

        if (long != null) {
            _queryParams.long = long.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SpotApiEnvironment.Default,
                `friends/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as SpotApi.GetFriendsIdResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new SpotApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new SpotApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SpotApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SpotApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SpotApiTimeoutError("Timeout exceeded when calling GET /friends/{id}.");
            case "unknown":
                throw new errors.SpotApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
